name: CI

on: [push, pull_request]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test-parser:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false
      - name: Run tests
        uses: tree-sitter/parser-test-action@v3
        with:
          generate: false
          test-rust: true
          test-node: true
          node-version: "22.x"
          test-python: true
          test-go: true
          go-version: "1.23"
          test-swift: ${{runner.os == 'macOS'}}
  parse-examples:
    name: Parse examples
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false
      - name: Parse examples
        uses: tree-sitter/parse-action@v4
        with:
          files-list: test/files.txt
          invalid-files-list: test/invalid-files.txt
  build-cmake:
    name: CMake build
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false
      - name: Configure
        run: cmake -B build
      - name: Build
        run: cmake --build build
  build-make:
    name: Make build
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Build
        run: make
